### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by ranjiewwen** [SaeidYazdani/PedestrainPatternRecognition#1]
hello , i am learn the code; now  i can run the code,but i don't konw the dataset,so which dataset do you choose?

**Comment by ranjiewwen** [comment]
more, can you wirte a detail readme.md  ； so other people can learn easy!

**Comment by SaeidYazdani** [comment]
I'll do a readme later :P but for now, you can get the datasets from here (you have to pay attention to their terms and conditions)

http://www.gavrila.net/Datasets/datasets.html

**Comment by ranjiewwen** [comment]
thanks
